apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ea2die15c-go
  janus-idp.io/tekton: ea2die15c-go
  backstage.io/kubernetes-id: ea2die15c-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ea2die15c-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
